artifacts_root: artifacts
data_injection:
   root_dir: artifacts/data_injection
   source_url: https://github.com/Sujal786Ninawe/Text_Summarization/raw/refs/heads/main/Dataset_text_summarization.zip
   local_data_file: artifacts/data_injection/data.zip
   unzip_dir: artifacts/data_injection